name: Playwright Tests CI

on:
  schedule:
    - cron: '0 7 * * *'  # Run daily at 7am UTC (3AM EST)
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Run Playwright Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10

    # This sets the PORT globally in this job
    env:
      PORT: 4173

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # or whatever version you're using

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Start React/Vite App
        run: npm run dev &
        env:
          PORT: ${{ env.PORT }}
          BROWSER: none  # Prevent React from trying to open a browser

      - name: Wait for app to be ready
        run: npx wait-on http://localhost:${{ env.PORT }}

      - name: Run Playwright Tests
        run: npx playwright test

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
